FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y && apt-get install -y curl python3 python3-pip vim git

WORKDIR /app
ADD . /app

RUN pip3 install -r requirements.txt

EXPOSE 8080
CMD python3 app.py
