apiVersion: v1
kind: Pod
metadata:
  name: multi-gpu-job-2
  labels:
    workload: training
spec:
  restartPolicy: Never
  containers:
    - name: trainer
      image: ubuntu:22.04
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/gpu: 4
