apiVersion: v1
kind: Pod
metadata:
  name: multi-gpu-job
  labels:
    workload: training
spec:
  restartPolicy: Never
  containers:
    - name: trainer
      image: ubuntu:22.04
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/gpu: 4            # cały node (gdy gpuCount: 4 w topology)
          cpu: "8"
          memory: 16Gi
