apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-demo
  labels:
    app: taints-demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: taints-demo
  template:
    metadata:
      labels:
        app: taints-demo
    spec:
      # Odkomentuj tolerations po zrobieniu `kubectl taint` na node (patrz task.md).
      # Pod BEZ tolerations nie zostanie zescheduleowany na tainted node.
      #tolerations:
      #- key: "dedicated"
      #  operator: "Equal"
      #  value: "workshop"
      #  effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
          - containerPort: 80
        resources:
          requests: { cpu: 50m, memory: 64Mi }
          limits:   { cpu: 200m, memory: 128Mi }
