apiVersion: v1
kind: Pod
metadata:
  name: training-medium
  labels:
    mig-demo: "true"
    mig-profile: 3g.20gb
spec:
  containers:
    - name: trainer
      image: ubuntu:22.04
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/mig-3g.20gb: 1
